### ISSUE TITLE
Cyclotron Installation on node v7.2 npm 3.10.9 

### ISSUE THREAD

**Issue by lshahar** [ExpediaInceCommercePlatform/cyclotron#11]
I have try to install cyclotron on Debian Jessie
npm -v  3.10.9
node -v v7.2.0

I got the following error:
root@15e0daa602b2:~/cyclotron-1.43.0/cyclotron-site# gulp server
[11:27:02] Requiring external module coffee-script/register
/root/cyclotron-1.43.0/cyclotron-site/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
  at Object.<anonymous> (/root/cyclotron-1.43.0/cyclotron-site/node_modules/socket.io/lib/store.js:35:41)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (/root/cyclotron-1.43.0/cyclotron-site/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/root/cyclotron-1.43.0/cyclotron-site/node_modules/socket.io/lib/manager.js:16:13)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (/root/cyclotron-1.43.0/cyclotron-site/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/root/cyclotron-1.43.0/cyclotron-site/node_modules/socket.io/lib/socket.io.js:87:19)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (/root/cyclotron-1.43.0/cyclotron-site/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/root/cyclotron-1.43.0/cyclotron-site/node_modules/socket.io/index.js:8:18)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (/root/cyclotron-1.43.0/cyclotron-site/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/root/cyclotron-1.43.0/cyclotron-site/node_modules/karma/lib/server.js:1:72)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (/root/cyclotron-1.43.0/cyclotron-site/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/root/cyclotron-1.43.0/cyclotron-site/node_modules/karma/lib/index.js:3:18)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (/root/cyclotron-1.43.0/cyclotron-site/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/root/cyclotron-1.43.0/cyclotron-site/gulpfile.coffee:50:9)
  at Object.<anonymous> (/root/cyclotron-1.43.0/cyclotron-site/gulpfile.coffee:1:1)
  at Module._compile (module.js:571:32)
  at Object.loadFile (/root/cyclotron-1.43.0/cyclotron-site/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/root/cyclotron-1.43.0/cyclotron-site/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)
  at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
  at module.exports (/usr/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)
  at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:190:9)
  at /usr/lib/node_modules/gulp/node_modules/liftoff/index.js:164:9
  at /usr/lib/node_modules/gulp/node_modules/v8flags/index.js:108:14
  at /usr/lib/node_modules/gulp/node_modules/v8flags/index.js:36:12
  at /usr/lib/node_modules/gulp/node_modules/v8flags/index.js:47:7
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
  at Module.runMain (module.js:607:11)
  at run (bootstrap_node.js:420:7)
  at startup (bootstrap_node.js:139:9)
  at bootstrap_node.js:535:3

**Comment by baumandm** [comment]
I think this is due to an out-of-date version of Karma.  I just pushed a change which upgraded the versions, can you `npm install` and try again?

**Comment by lshahar** [comment]
solved

**Comment by lshahar** [comment]
There is still issue with the API, Once i try to use the API for example call 'tags' the API stuck.
I downgrade the Node version to 6 and it's solved.

**Comment by baumandm** [comment]
Hi @lshahar, I just pushed a release that should fix the API on Node 7.x, can you pull and try again?

**Comment by DanielDent** [comment]
Current npm install output:

> npm WARN deprecated gulp-minify-css@1.0.0: Please use gulp-clean-css
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm WARN deprecated jade@1.9.2: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer

graceful-fs warns that it isn't compatible with node 7

**Comment by baumandm** [comment]
I've tested pretty thoroughly on Node 7 and haven't run into any issues, so hopefully these are just warnings and can be safely ignored.

It looks like Gulp 3.9.1 is a major culprit behind most of these warnings, but that's the latest released version so I'll have to wait for the next release.  However, I did find a few other dependencies which are out of date and logging `WARN deprecated` messages, which I will upgraded ASAP.
