### ISSUE TITLE
cyclotron-svc> npm install fails. Can't find Python executable.

### ISSUE THREAD

**Issue by omkarkhair** [ExpediaInceCommercePlatform/cyclotron#16]
I'm installing cyclotron on Windows, and it seems there is a dependency on Python for the 'dtrace-provider' module.

```
C:\git\cyclotron\cyclotron-svc>npm install

> dtrace-provider@0.2.8 install C:\git\cyclotron\cyclotron-svc\node_modules\dtrace-provider
> node-gyp rebuild


C:\git\cyclotron\cyclotron-svc\node_modules\dtrace-provider>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:112:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\git\cyclotron\cyclotron-svc\node_modules\dtrace-provider
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.2.8 (node_modules\dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.2.8 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by omkarkhair** [comment]
Update: I installed Python 2.7 with python in PATH and the npm install worked. There is a dependency on Python on the Windows platform.

**Comment by baumandm** [comment]
Thanks for the update @omkarkhair.  I'll get this added to the installation docs.

**Comment by baumandm** [comment]
Running the following command from the [node-gyp documentation](https://github.com/nodejs/node-gyp#installation) resolves this on Windows:

    npm install --global --production windows-build-tools

Looks like it installs Python 2.7 and Visual Studio Build Tools.

**Comment by omkarkhair** [comment]
Great. Thanks :)

Just to be clear it would be nice to have the documentation on the project website remain inline with the project Readme. http://www.cyclotron.io/gettingstarted.html

**Comment by baumandm** [comment]
Updated!
