### ISSUE TITLE
Installation error occured at cyclotron-site

### ISSUE THREAD

**Issue by saprophagist** [ExpediaInceCommercePlatform/cyclotron#52]
After "npm install" command, "gulp server" command generates an exception.
Exception:
```
...
[11:00:26] bower install desandro-matches-selector#2.0.2
[11:00:26] bower install angular-cookies#1.4.9
[11:00:26] bower install angular-mocks#1.4.9
[11:00:32] 'bower-install' errored after 27 s
[11:00:32] Error: calling transform done when ws.length != 0
    at done (.../cyclotron-master/cyclotron-site/node_modules/gulp-bower/node_modules/readable-stream/lib/_stream_transform.js:204:11)
    at DestroyableTransform.<anonymous> (.../cyclotron-master/cyclotron-site/node_modules/gulp-bower/node_modules/readable-stream/lib/_stream_transform.js:139:7)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at DestroyableTransform.emit (events.js:208:7)
    at Walker.<anonymous> (.../cyclotron-master/cyclotron-site/node_modules/gulp-bower/index.js:245:16)
    at emitNone (events.js:106:13)
    at Walker.emit (events.js:208:7)
    at Walker._wNext (.../cyclotron-master/cyclotron-site/node_modules/walk/lib/walk.js:252:10)
    at Walker._wNext (.../cyclotron-master/cyclotron-site/node_modules/walk/lib/walk.js:247:17)
    at Walker._wNext (.../cyclotron-master/cyclotron-site/node_modules/walk/lib/walk.js:247:17)
    at Walker._wNext (.../cyclotron-master/cyclotron-site/node_modules/walk/lib/walk.js:247:17)
    at Walker._wNext (.../cyclotron-master/cyclotron-site/node_modules/walk/lib/walk.js:247:17)
    at Walker._wNext (.../cyclotron-master/cyclotron-site/node_modules/walk/lib/walk.js:247:17)
    at Walker._wOnEmitDone (.../cyclotron-master/cyclotron-site/node_modules/walk/lib/walk.js:122:8)
    at nextWhenReady (.../cyclotron-master/cyclotron-site/node_modules/walk/lib/node-type-emitter.js:69:29)
    at Object.emitPluralEvents [as emitNodeTypeGroups] (.../cyclotron-master/cyclotron-site/node_modules/walk/lib/node-type-emitter.js:77:5)
    at Walker._wPostFilesHandler (.../cyclotron-master/cyclotron-site/node_modules/walk/lib/walk.js:132:17)
    at .../cyclotron-master/cyclotron-site/node_modules/foreachasync/forEachAsync.js:15:16
    at Array.forEach (<anonymous>:null:null)
    at Walker.next [as _wCurFileCallback] (.../cyclotron-master/cyclotron-site/node_modules/foreachasync/forEachAsync.js:14:15)
    at nextWhenReady (.../cyclotron-master/cyclotron-site/node_modules/walk/lib/node-type-emitter.js:52:29)
    at .../cyclotron-master/cyclotron-site/node_modules/gulp-bower/index.js:239:13
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

[11:00:32] 'vendor' errored after 27 s
[11:00:32] 'build' errored after 27 s
[11:00:32] 'server' errored after 27 s
```

OS: Ubuntu 18.04
Nodejs: 8.10.0~dfsg-2ubuntu0.4
npm: 3.5.2-0ubuntu4

What could be the reason? Thanks for your attention. I’m looking forward to your reply.

**Comment by baumandm** [comment]
Hi @saprophagist, the closest Docker image I could find for this version of Node is `node:8.16.2-jessie`, which is slightly little newer.  Unfortunately I couldn't reproduce this error and everything worked fine.  I also didn't have much luck finding any related issues.

I suspect there's a compatibility issue on your specific version of Node, but `gulp-bower` is now deprecated and I'm not expecting them to fix any issues on their side.

I think the best solution would be to upgrade to a newer version of Node.js (especially as 8 is reaching EOL by the end of the year).  If that's not possible for you, you can try the following:
1) Delete `package-lock.json` and run `npm install` again, in case the locked dependencies are causing issues
2) Fiddle with the `gulp-bower` version, possibly an older version would be compatible: https://www.npmjs.com/package/gulp-bower

**Comment by saprophagist** [comment]
Hi @baumandm, updating Node (v10.16.1) doesn't work. Then tried first solution (rm package-lock.json and reinstall) with no success. It seems like only 1.48.0 release works for me. Thank you for your interest :)
